import '../styles/globals.css'
import  AuthSessionProvider  from '@/lib/AuthSessionProvider'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthSessionProvider>
      <body>{children}</body>

      </AuthSessionProvider>
    </html>
  )
}

