import '../styles/globals.css'
import  AuthSessionProvider  from '@/lib/AuthSessionProvider'
import Nav from '@/components/Nav'
import LayoutDesign from '@/components/LayoutDesign'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthSessionProvider>
      <body>
        <LayoutDesign>
        {children}
        </LayoutDesign>
        </body>

      </AuthSessionProvider>
    </html>
  )
}

